config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'jam/new', to: 'jam#new', as: :jam_new
  post 'jam', to: 'jam#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jam_controller.rb
# app/controllers/jam_controller.rb

class JamController < ApplicationController
  def new
  end

  def create
    if check_validity(params[:input])
      @bassline = generate_random_bassline
      @drum_pattern = generate_random_drum_pattern
      render :show
    else
      render json: { message: 'Invalid input' }, status: :unprocessable_entity
    end
  end

  private

  def check_validity(input)
    input.downcase.include?('play')
  end

  def generate_random_bassline
    ['A#', 'C', 'D#', 'F', 'G#'].sample(4).join(' ')
  end

  def generate_random_drum_pattern
    ['kick', 'snare', 'hi-hat', 'ride', 'crash'].sample(4).join(' ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jam_helper.rb
module JamHelper
end

app/views/jam/new.html.haml
%h1 The Jam Machine

= form_with url: jam_path, method: :post, local: true do |f|
  = f.label :input, 'Enter your request:'
  %br/
  = f.text_area :input, rows: 4, cols: 50
  %br/
  = f.submit 'Generate music'

app/views/jam/show.html.haml
%h1 Generated Music

%h2 Bassline:
%p= @bassline

%h2 Drum Pattern:
%p= @drum_pattern

= link_to 'Try again', jam_new_path